language: node_js

node_js:
  - "11.5.0"

services:
  - docker

notifications:
  slack: devopslille:HcTQJRlD5FHkVG5YWqKYZuzs

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test

after_success:
  - yarn coverage

before_deploy:
  # Set up git user name and tag this commit
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      git config --local user.name "travis@travis-ci.org"
      git config --local user.email "Travis CI"
      export TRAVIS_TAG=$(jq -r ".version" package.json)
      git tag -f $TRAVIS_TAG
    fi

deploy:
  - provider: script
    script: bash scripts/sentry.sh
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: $TRAVIS_TAG
    overwrite: true
    on:
      branch: master
  - provider: script
    script: bash scripts/docker_push.sh
    on:
      branch: master
